version: '3.8'
services:
  botapi:
    build:
      context: ./bot/
      target: ${MODE}
    container_name: botapi
    volumes:
      - ./bot/:/usr/src/app
    env_file:
        - .env
    restart: always
    init: true
    command: flask --app server run --port 8000 --host 0.0.0.0 --debug
  botapp:
    build:
      context: ./bot/
      target: ${MODE}
    container_name: botapp
    env_file:
        - .env
    volumes:
      - ./bot/:/usr/src/app
    restart: always
    init: true
    command: python main.py
  botserver:
    image: nginx:1.25.3
    container_name: botserver
    volumes:
      - ./nginx/logs/:/var/log/nginx/
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - botapi
    restart: always



